name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: EduardaSantosDiniz
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
